before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - echo "skipping tests"

jobs:
  include:
    - name: Nette Code Checker
      install:
        - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      script:
        - php temp/code-checker/code-checker --strict-types
      language: php
      php:
        - 7.4


    - name: Nette Coding Standard
      install:
        - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
      script:
        - php temp/coding-standard/ecs check app --config temp/coding-standard/coding-standard-php71.yml
      language: php
      php:
        - 7.4


    - name: Static Analysis
      script:
        - composer run-script phpstan
      language: php
      php:
        - 7.4
