language: php
php:
  - 8.0

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - echo "skipping tests"

jobs:
  include:
    - name: Nette Code Checker
      install:
        - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      script:
        - php temp/code-checker/code-checker --strict-types


    - name: Nette Coding Standard
      install:
        - travis_retry composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress
      script:
        - php temp/coding-standard/ecs check --preset php71


    - name: Static Analysis
      script:
        - composer run-script phpstan
